/** The Tally design-system component kit. Import from '@/components/ui'. */
export { Avatar, type AvatarProps } from './Avatar'
export { Button, type ButtonProps } from './Button'
export { Card, SectionHeader, type CardProps } from './Card'
export { CategoryTile, type CategoryTileProps } from './CategoryTile'
export { Chip, type ChipProps } from './Chip'
export { CategoryIcon } from './CategoryIcon'
export { ICON_REGISTRY, resolveCategoryIcon, type IconEntry } from './icons'
export { IconPicker, type IconPickerProps } from './IconPicker'
export { ListRow, ListDivider, type ListRowProps } from './ListRow'
export { Modal, type ModalProps } from './Modal'
export { SegmentedControl, type SegmentOption, type SegmentedControlProps } from './SegmentedControl'
export { StatCard, type StatCardProps } from './StatCard'
export { EmptyState, ErrorState, LoadingRows, Skeleton } from './States'
